# Generated by Django 5.1 on 2024-08-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cours_intro',
            new_name='course_intro',
        ),
    ]
