# Generated by Django 5.1 on 2024-08-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_comment_alter_course_course_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='courses.comments'),
        ),
    ]
