# Generated by Django 5.1 on 2024-08-29 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='viewed_by',
        ),
        migrations.AddField(
            model_name='lessons',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
