# Generated by Django 5.1 on 2024-08-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_lessons_viewed_by_lessons_viewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to='courses.course'),
            preserve_default=False,
        ),
    ]
