# Generated by Django 5.1 on 2024-08-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_comment_comments_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='creator',
        ),
    ]
