# Generated by Django 5.1 on 2024-08-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_user_comments_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('creator', 'course')},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='course',
        ),
        migrations.AddField(
            model_name='comments',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comment', to='courses.lessons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
