# Generated by Django 5.1 on 2024-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
