# Generated by Django 5.1 on 2024-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='slug',
            field=models.SlugField(default='one'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
