# Generated by Django 5.1 on 2024-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newuser_slug_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
